import type { UnifiedDemoData } from "@/features/unified-dashboard/types";

/* Anotado com o tipo (em vez de `satisfies`) para que os funis fiquem como
   Record<string, FunnelDefinition>: o provedor procura o funil por um id que
   vem do storage, ou seja, uma string qualquer. */
export const unifiedDemoData: UnifiedDemoData = {
  operations: {
    alpha: {
      id: "alpha",
      name: "Operação Alpha",
      product: "Curso Tráfego Pago Pro",
      offer: "Oferta principal",
      owner: "Marina Costa",
      status: "Saudável",
      confidence: 94,
      kpis: {
        cash: 76800,
        netRevenue: 74400,
        contributionProfit: 15700,
        margin: 0.211,
        mer: 1.55,
        ncCac: 74,
        orders: 784,
        approval: 0.942,
        ticket: 94.9,
      },
      networks: [
        {
          id: "meta",
          name: "Meta Ads",
          color: "#f5f5f5",
          spend: 28000,
          platformRevenue: 43200,
          checkoutRevenue: 39200,
          profit: 7400,
          newCustomers: 341,
          purchases: 403,
          impressions: 2180000,
          clicks: 45780,
          status: "Atenção",
        },
        {
          id: "google",
          name: "Google Ads",
          color: "#a8a8a8",
          spend: 14000,
          platformRevenue: 27100,
          checkoutRevenue: 25200,
          profit: 6800,
          newCustomers: 229,
          purchases: 278,
          impressions: 740000,
          clicks: 29600,
          status: "Saudável",
        },
        {
          id: "youtube",
          name: "YouTube Ads",
          color: "#6a6a6a",
          spend: 6000,
          platformRevenue: 11200,
          checkoutRevenue: 10000,
          profit: 1500,
          newCustomers: 81,
          purchases: 103,
          impressions: 950000,
          clicks: 13300,
          status: "Estável",
        },
      ],
      campaigns: [
        {
          id: "a1",
          network: "meta",
          name: "Escala Produto A",
          objective: "Vendas",
          spend: 8500,
          platformRevenue: 17050,
          checkoutRevenue: 15300,
          profit: 3200,
          purchases: 126,
          newCustomers: 102,
          impressions: 620000,
          clicks: 14880,
          hook: 0.31,
          hold: 0.19,
          frequency: 2.4,
          status: "Manter",
        },
        {
          id: "a2",
          network: "meta",
          name: "Teste Criativos — Agosto",
          objective: "Teste",
          spend: 4200,
          platformRevenue: 5400,
          checkoutRevenue: 4800,
          profit: -600,
          purchases: 39,
          newCustomers: 33,
          impressions: 410000,
          clicks: 7790,
          hook: 0.22,
          hold: 0.11,
          frequency: 3.6,
          status: "Reduzir",
        },
        {
          id: "a3",
          network: "meta",
          name: "Remarketing 14 dias",
          objective: "Remarketing",
          spend: 2100,
          platformRevenue: 6600,
          checkoutRevenue: 5900,
          profit: 2000,
          purchases: 44,
          newCustomers: 11,
          impressions: 145000,
          clicks: 5220,
          hook: 0.37,
          hold: 0.24,
          frequency: 5.1,
          status: "Validar",
        },
        {
          id: "a4",
          network: "google",
          name: "Pesquisa — Marca",
          objective: "Pesquisa",
          spend: 3800,
          platformRevenue: 10100,
          checkoutRevenue: 9400,
          profit: 3200,
          purchases: 88,
          newCustomers: 61,
          impressions: 92000,
          clicks: 8900,
          hook: null,
          hold: null,
          frequency: 1.3,
          status: "Escalar",
        },
        {
          id: "a5",
          network: "google",
          name: "Performance Max",
          objective: "PMax",
          spend: 6700,
          platformRevenue: 11100,
          checkoutRevenue: 10200,
          profit: 2500,
          purchases: 112,
          newCustomers: 103,
          impressions: 410000,
          clicks: 12700,
          hook: null,
          hold: null,
          frequency: 2.1,
          status: "Manter",
        },
        {
          id: "a6",
          network: "youtube",
          name: "VSL — Prospecção",
          objective: "Vídeo",
          spend: 4100,
          platformRevenue: 7900,
          checkoutRevenue: 6900,
          profit: 1300,
          purchases: 72,
          newCustomers: 57,
          impressions: 690000,
          clicks: 9100,
          hook: 0.34,
          hold: 0.21,
          frequency: 2.2,
          status: "Manter",
        },
      ],
      funnels: {
        main: {
          id: "main",
          name: "Funil Geral",
          type: "Infoproduto",
          stages: [
            ["Impressões", 17991, 0, 45.97],
            ["Cliques no link", 463, 0.0257, 1.79],
            ["Page view", 415, 0.8963, 1.99],
            ["Início checkout", 41, 0.0988, 20.17],
            ["Compras", 12, 0.2927, 68.92],
            ["Aprovadas", 11, 0.9167, 75.18],
            ["Liquidadas", 10, 0.9091, 82.7],
          ],
          demographics: [47, 21, 18, 9, 5],
          video: [0.0849, 0.0478, 0.0266, 0.0137],
        },
        vsl: {
          id: "vsl",
          name: "VSL Principal",
          type: "Vídeo",
          stages: [
            ["Impressões", 45600, 0, 31.2],
            ["Visualização 3s", 12800, 0.2807, 0.11],
            ["Visualização 25%", 6200, 0.4844, 0.23],
            ["Clique", 1150, 0.1855, 1.23],
            ["Checkout", 126, 0.1096, 11.24],
            ["Compras", 36, 0.2857, 39.32],
            ["Liquidadas", 33, 0.9167, 42.89],
          ],
          demographics: [39, 25, 20, 11, 5],
          video: [0.28, 0.136, 0.071, 0.032],
        },
        remarketing: {
          id: "remarketing",
          name: "Remarketing 7 dias",
          type: "Remarketing",
          stages: [
            ["Pessoas impactadas", 8600, 0, 28.9],
            ["Cliques", 840, 0.0977, 0.74],
            ["Page view", 760, 0.9048, 0.82],
            ["Checkout", 138, 0.1816, 4.5],
            ["Compras", 44, 0.3188, 14.11],
            ["Aprovadas", 42, 0.9545, 14.78],
            ["Liquidadas", 41, 0.9762, 15.14],
          ],
          demographics: [51, 19, 16, 9, 5],
          video: [0.12, 0.071, 0.044, 0.028],
        },
      },
    },
    beta: {
      id: "beta",
      name: "Operação Beta",
      product: "Produto recorrente",
      offer: "Oferta de assinatura",
      owner: "Lucas Vieira",
      status: "Atenção",
      confidence: 87,
      kpis: {
        cash: 45100,
        netRevenue: 43200,
        contributionProfit: 7300,
        margin: 0.169,
        mer: 1.39,
        ncCac: 86,
        orders: 469,
        approval: 0.887,
        ticket: 92.1,
      },
      networks: [
        {
          id: "meta",
          name: "Meta Ads",
          color: "#f5f5f5",
          spend: 17500,
          platformRevenue: 25700,
          checkoutRevenue: 22400,
          profit: 2900,
          newCustomers: 205,
          purchases: 241,
          impressions: 1440000,
          clicks: 30240,
          status: "Atenção",
        },
        {
          id: "google",
          name: "Google Ads",
          color: "#a8a8a8",
          spend: 9200,
          platformRevenue: 18300,
          checkoutRevenue: 17100,
          profit: 4100,
          newCustomers: 139,
          purchases: 166,
          impressions: 510000,
          clicks: 19890,
          status: "Saudável",
        },
        {
          id: "youtube",
          name: "YouTube Ads",
          color: "#6a6a6a",
          spend: 4300,
          platformRevenue: 6900,
          checkoutRevenue: 6100,
          profit: 300,
          newCustomers: 49,
          purchases: 62,
          impressions: 630000,
          clicks: 8400,
          status: "Crítico",
        },
      ],
      campaigns: [
        {
          id: "b1",
          network: "meta",
          name: "Escala Oferta B",
          objective: "Vendas",
          spend: 9800,
          platformRevenue: 15700,
          checkoutRevenue: 14100,
          profit: 2200,
          purchases: 151,
          newCustomers: 132,
          impressions: 770000,
          clicks: 16100,
          hook: 0.29,
          hold: 0.16,
          frequency: 2.9,
          status: "Manter",
        },
        {
          id: "b2",
          network: "meta",
          name: "Teste UGC",
          objective: "Teste",
          spend: 4200,
          platformRevenue: 5100,
          checkoutRevenue: 4300,
          profit: -400,
          purchases: 47,
          newCustomers: 39,
          impressions: 390000,
          clicks: 7200,
          hook: 0.21,
          hold: 0.1,
          frequency: 4.2,
          status: "Reduzir",
        },
        {
          id: "b3",
          network: "google",
          name: "Pesquisa Produto B",
          objective: "Pesquisa",
          spend: 4700,
          platformRevenue: 10300,
          checkoutRevenue: 9800,
          profit: 2700,
          purchases: 94,
          newCustomers: 72,
          impressions: 156000,
          clicks: 9400,
          hook: null,
          hold: null,
          frequency: 1.4,
          status: "Escalar",
        },
        {
          id: "b4",
          network: "google",
          name: "Performance Max B",
          objective: "PMax",
          spend: 4500,
          platformRevenue: 8000,
          checkoutRevenue: 7300,
          profit: 1400,
          purchases: 72,
          newCustomers: 67,
          impressions: 354000,
          clicks: 10490,
          hook: null,
          hold: null,
          frequency: 2,
          status: "Manter",
        },
        {
          id: "b5",
          network: "youtube",
          name: "VSL Beta",
          objective: "Vídeo",
          spend: 4300,
          platformRevenue: 6900,
          checkoutRevenue: 6100,
          profit: 300,
          purchases: 62,
          newCustomers: 49,
          impressions: 630000,
          clicks: 8400,
          hook: 0.19,
          hold: 0.1,
          frequency: 4.4,
          status: "Pausar",
        },
      ],
      funnels: {
        subscription: {
          id: "subscription",
          name: "Oferta de Assinatura",
          type: "Recorrência",
          stages: [
            ["Impressões", 22670, 0, 42.1],
            ["Cliques no link", 667, 0.0294, 1.43],
            ["Page view", 598, 0.8966, 1.6],
            ["Teste grátis", 104, 0.1739, 9.18],
            ["Assinaturas", 18, 0.1731, 53.02],
            ["Renovação M2", 11, 0.6111, 86.76],
            ["Renovação M3", 7, 0.6364, 136.34],
          ],
          demographics: [44, 24, 18, 9, 5],
          video: [0.11, 0.064, 0.036, 0.019],
        },
        webinar: {
          id: "webinar",
          name: "Webinar Automático",
          type: "Webinar",
          stages: [
            ["Impressões", 31200, 0, 38.4],
            ["Cliques", 980, 0.0314, 1.22],
            ["Inscrições", 410, 0.4184, 2.93],
            ["Compareceram", 172, 0.4195, 6.98],
            ["Oferta vista", 138, 0.8023, 8.7],
            ["Compras", 26, 0.1884, 46.15],
            ["Liquidadas", 24, 0.9231, 50],
          ],
          demographics: [37, 27, 20, 11, 5],
          video: [0.17, 0.104, 0.064, 0.031],
        },
      },
    },
  },
  products: [
    {
      id: "p1",
      name: "Curso Tráfego Pago Pro",
      type: "Digital",
      price: 297,
      stock: "Ilimitado",
      status: "Publicado",
    },
    {
      id: "p2",
      name: "Mentoria Individual",
      type: "Serviço",
      price: 497,
      stock: "24 vagas",
      status: "Publicado",
    },
    {
      id: "p3",
      name: "E-book Escala Criativa",
      type: "Digital",
      price: 19.9,
      stock: "Ilimitado",
      status: "Publicado",
    },
    {
      id: "p4",
      name: "Template Pack Anúncios",
      type: "Digital",
      price: 29.9,
      stock: "Ilimitado",
      status: "Rascunho",
    },
  ],
  orders: [
    {
      ref: "#IN-1042",
      customer: "Mariana S.",
      product: "Curso Tráfego Pago Pro",
      total: 297,
      status: "Pago",
      gateway: "Broski",
      date: "28/07 14:32",
    },
    {
      ref: "#IN-1041",
      customer: "João P.",
      product: "E-book Escala Criativa",
      total: 19.9,
      status: "Pago",
      gateway: "Broski",
      date: "28/07 13:54",
    },
    {
      ref: "#IN-1040",
      customer: "Carla M.",
      product: "Mentoria Individual",
      total: 497,
      status: "Pendente",
      gateway: "Broski",
      date: "28/07 12:18",
    },
    {
      ref: "#IN-1039",
      customer: "Renato F.",
      product: "Curso Tráfego Pago Pro",
      total: 297,
      status: "Recusado",
      gateway: "Broski",
      date: "28/07 11:46",
    },
    {
      ref: "#IN-1038",
      customer: "Alice R.",
      product: "Template Pack Anúncios",
      total: 29.9,
      status: "Pago",
      gateway: "Broski",
      date: "28/07 10:21",
    },
  ],
  customers: [
    {
      name: "Mariana Silva",
      email: "mariana@email.com",
      orders: 4,
      revenue: 1188,
      consent: true,
      last: "28/07/2026",
    },
    {
      name: "João Pereira",
      email: "joao@email.com",
      orders: 2,
      revenue: 316.9,
      consent: true,
      last: "28/07/2026",
    },
    {
      name: "Carla Mendes",
      email: "carla@email.com",
      orders: 1,
      revenue: 497,
      consent: false,
      last: "28/07/2026",
    },
    {
      name: "Renato Freitas",
      email: "renato@email.com",
      orders: 3,
      revenue: 891,
      consent: true,
      last: "27/07/2026",
    },
  ],
  transactions: [
    {
      date: "28/07",
      description: "Venda #IN-1042",
      category: "Vendas",
      type: "entrada",
      value: 297,
    },
    {
      date: "28/07",
      description: "Taxa Broski",
      category: "Taxas",
      type: "saida",
      value: 8.6,
    },
    {
      date: "27/07",
      description: "Repasse Broski",
      category: "Repasses",
      type: "entrada",
      value: 1840,
    },
    {
      date: "27/07",
      description: "Reembolso — Carla M.",
      category: "Reembolsos",
      type: "saida",
      value: 497,
    },
    {
      date: "26/07",
      description: "Assinatura ferramenta de anúncios",
      category: "Despesas operacionais",
      type: "saida",
      value: 350,
    },
  ],
  notifications: [
    {
      title: "Venda aprovada",
      body: "Pedido #IN-1042 no valor de R$ 297,00.",
      time: "há 8 min",
      tone: "good",
    },
    {
      title: "Pagamento recusado",
      body: "Pedido #IN-1039 foi recusado pelo processador.",
      time: "há 42 min",
      tone: "bad",
    },
    {
      title: "CPA acima da meta",
      body: "YouTube Ads ultrapassou o limite configurado.",
      time: "há 1h",
      tone: "warn",
    },
    {
      title: "Sincronização concluída",
      body: "Meta Ads e Google Ads atualizados.",
      time: "há 2h",
      tone: "info",
    },
  ],
} satisfies UnifiedDemoData;

/**
 * Sem integrações reais, as páginas continuam montadas para configuração e
 * navegação, porém nenhuma métrica de exemplo é apresentada como se fosse
 * informação da empresa.
 */
function zeroUnifiedMetrics(value: unknown): void {
  if (Array.isArray(value)) {
    value.forEach((nested, index) => {
      if (typeof nested === "number") {
        value[index] = 0;
      } else {
        zeroUnifiedMetrics(nested);
      }
    });
    return;
  }
  if (!value || typeof value !== "object") return;

  const record = value as Record<string, unknown>;
  for (const [key, nested] of Object.entries(record)) {
    if (typeof nested === "number") {
      record[key] = 0;
    } else {
      zeroUnifiedMetrics(nested);
    }
  }
}

zeroUnifiedMetrics(unifiedDemoData.operations);

// Entidades inventadas são removidas em vez de aparecerem como registros reais.
unifiedDemoData.products.length = 0;
unifiedDemoData.orders.length = 0;
unifiedDemoData.customers.length = 0;
unifiedDemoData.transactions.length = 0;
unifiedDemoData.notifications.length = 0;
