/** Reviewed additive migrations, fixed at build time. No arbitrary SQL input. */
export const registeredMigrations = [
  {
    name: "0007_funnel_storage.sql",
    sql: '-- Authenticated server endpoints enforce workspace role and user ownership.\nCREATE TABLE IF NOT EXISTS "funnel_vaults" (\n  "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE,\n  "user_id" text NOT NULL,\n  "revision" uuid NOT NULL,\n  "envelope" jsonb NOT NULL CHECK (octet_length("envelope"::text) <= 4000000),\n  "updated_at" timestamptz DEFAULT now() NOT NULL,\n  PRIMARY KEY ("workspace_id", "user_id")\n);\nCREATE TABLE IF NOT EXISTS "funnel_vault_history" (\n  "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE,\n  "user_id" text NOT NULL,\n  "revision" uuid NOT NULL,\n  "envelope" jsonb NOT NULL CHECK (octet_length("envelope"::text) <= 4000000),\n  "created_at" timestamptz DEFAULT now() NOT NULL,\n  PRIMARY KEY ("workspace_id", "user_id", "revision")\n);\nCREATE INDEX IF NOT EXISTS "funnel_vault_history_recent_idx" ON "funnel_vault_history" ("workspace_id", "user_id", "created_at" DESC);\nCREATE TABLE IF NOT EXISTS "funnel_packages" (\n  "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE,\n  "user_id" text NOT NULL,\n  "funnel_id" text NOT NULL,\n  "node_id" text NOT NULL,\n  "product_id" text DEFAULT \'\' NOT NULL,\n  "filename" text NOT NULL,\n  "sha256" text NOT NULL,\n  "size_bytes" integer NOT NULL CHECK ("size_bytes" BETWEEN 1 AND 3000000),\n  "content" bytea NOT NULL CHECK (octet_length("content") = "size_bytes"),\n  "updated_at" timestamptz DEFAULT now() NOT NULL,\n  PRIMARY KEY ("workspace_id", "user_id", "funnel_id", "node_id", "product_id")\n);\nALTER TABLE "funnel_vaults" ENABLE ROW LEVEL SECURITY;\nALTER TABLE "funnel_vault_history" ENABLE ROW LEVEL SECURITY;\nALTER TABLE "funnel_packages" ENABLE ROW LEVEL SECURITY;\nREVOKE ALL ON "funnel_vaults", "funnel_vault_history", "funnel_packages" FROM PUBLIC;\nDO $$ BEGIN\n  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = \'anon\') THEN\n    REVOKE ALL ON "funnel_vaults", "funnel_vault_history", "funnel_packages" FROM anon;\n  END IF;\n  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = \'authenticated\') THEN\n    REVOKE ALL ON "funnel_vaults", "funnel_vault_history", "funnel_packages" FROM authenticated;\n  END IF;\nEND $$;\n',
  },
  {
    name: "0008_rate_limits.sql",
    sql: "-- Aplicada durante o deploy, nunca criada por uma requisição pública.\nCREATE TABLE IF NOT EXISTS rate_limit_buckets (\n  bucket_key varchar(64) PRIMARY KEY,\n  window_start timestamptz NOT NULL,\n  requests integer NOT NULL CHECK (requests > 0),\n  expires_at timestamptz NOT NULL\n);\nCREATE INDEX IF NOT EXISTS rate_limit_buckets_expiry_idx ON rate_limit_buckets (expires_at);\nALTER TABLE rate_limit_buckets ENABLE ROW LEVEL SECURITY;\n\n",
  },
] as const;
